server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/project_trained
  main:
    allow-circular-references: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

    #static-path-pattern: /static/**

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8

mybatis:
  type-aliases-package: com.fly.practicaltrainingproject.entity
  mapper-locations: classpath:/mappers/*.xml


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  page-size-zero: true


service:
  url:
    studentUrl: http://localhost:8082/student/
    orderUrl: http://localhost:8082/order/

knife4j:
  enable: true
  production: false


